# Generated by Django 5.1.5 on 2025-01-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("contact", models.CharField(max_length=10)),
                ("amount", models.IntegerField()),
                ("event", models.CharField(max_length=100)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
