# Generated by Django 5.1.5 on 2025-01-20 16:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsorship", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsor",
            name="payment_success",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="date_added",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
