# Generated by Django 5.1.5 on 2025-01-20 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sponsorship", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                ("transaction_id", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=100)),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                (
                    "sponsor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="sponsorship.sponsor",
                    ),
                ),
            ],
        ),
    ]
