# Generated by Django 5.1.5 on 2025-01-22 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
        ("sponsorship", "0002_sponsor_payment_success_alter_sponsor_date_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="sponsor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="sponsorship.sponsor",
            ),
        ),
    ]
